--- #YAML:1.0
name:                Date-Holidays-CA
version:             0.02
abstract:            Holidays for Canadian locales
license:             ~
author:              
    - Rick Scott <rick@shadowspar.dyndns.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    DateTime:                      0
    DateTime::Event::Easter:       0
    Test::Exception:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
